import StyledComponentsRegistry from "@/lib/registry";
import type { Metadata } from "next";
import localFont from "next/font/local";
import GlobalStyle from "@/styles/GlobalCss";
import RootLayoutStyle from "@/components/common/RootLayout";

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: "./PretendardVariable.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" className={myFont.className}>
      <body>
        <GlobalStyle />
        <StyledComponentsRegistry>
          <RootLayoutStyle>{children}</RootLayoutStyle>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
